###
POST {{auth_base_url}}/user/register
Content-Type: application/json

{
  "username": "test_user1",
  "password": "abc123"
}

###
GET {{auth_base_url}}/user/info/admin
Authorization: Bearer {{oauth2_token}}

###
POST {{auth_base_url}}/user/loginId
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

> {% client.global.set('loginId', response.body['data']) %}

###
# redirect_uri不可省略，其必须是SecurityConfig中所配置的client的redirectUri中的其中一个，否则报告400
GET http://localhost:8081/oauth2/authorize?response_type=code&client_id=oauth2-client1&scope=all&redirect_uri=https%3A%2F%2Fwww.baidu.com
X-Login-ID: {{loginId}}

> {%
　let resIsObject = (typeof response.body) === 'object' && response.body['data'] != null
  client.global.set('authorize_state', resIsObject ? response.body['data']['state'] : '')
%}

###
POST {{auth_base_url}}/oauth2/authorize
Content-Type: application/x-www-form-urlencoded
X-Login-ID: {{loginId}}

client_id=oauth2-client1&state={{authorize_state}}&scope=all

###
POST {{auth_base_url}}/oauth2/token
Content-Type: application/x-www-form-urlencoded
# Authorization的值为SecurityConfig中所配置的client的clientId与clientSecret（原文），用冒号拼接，然后base64编码
Authorization: Basic b2F1dGgyLWNsaWVudDE6MTIzNDU2

grant_type=authorization_code&code
=Vheh4cILNJEQz8m-hk5App5NYTaWkXNMM5i4DMIZXYbXQ0eNyBu71jN-p8IKCtogEPwrfB6r7SICqvX0gl25Cakq2dWPhh1-Y0OPp239bvZtFxq7jg3142QwAzT8VQ5T&redirect_uri=https%3A%2F%2Fwww.baidu.com

> {% client.global.set('oauth2_token', response.body['access_token']) %}

###
GET {{business1_base_url}}/res1
Authorization: Bearer {{oauth2_token}}

###
GET {{business1_base_url}}/res2
Authorization: Bearer {{oauth2_token}}

###
GET {{business2_base_url}}/res1
Authorization: Bearer {{oauth2_token}}
